### PR TITLE
web forms enable config

### LINKED ISSUE #2333: Swap URL based webforms feature flag to config.json
**Describe the bug**

- We currently enable web-forms via `webforms=true` in the URL.
- Users that access via projects landing page lose the URL param after clicking a project.
- Ideally we can configure webform usage for an instance, as part of the global config.
- I recently added a config.json file with styling info etc, which can use for other config.

**Expected behavior**

- The config is loaded into the common store at frontend load
- Set a boolean key `enableWebforms`.
- If true, entirely remove the 'Map Feature In ODK' button and only show the webforms button.
- Also rename 'Map In ODK Web Forms' on the button to something simple like 'Collect Data'.

### PR DESCRIPTION
**Pull request by DanielJDufour**
## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

Example: Fixes #2333 

## Describe this PR

Replace URL param with config.json for enabling web forms

## Screenshots

Screenshot 2025-04-03 at 8 16 48 PM

Screenshot 2025-04-03 at 8 17 10 PM

## Alternative Approaches Considered

none

## Review Guide

Notes for the reviewer. How to test this change?
- Go to mapper frontend (like http://mapper.fmtm.localhost:7050/1)
- Click on the map
- Click on a building
- See that only one red button appears (depending on whether enableWebforms is true or false in config.json)

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by DanielJDufour** [comment]
I should mention that I set the default enableWebforms to false, so ODK Collect will still be the default while we are still in development phase.

**Comment by DanielJDufour** [comment]
Also, I moved the common store setConfig call outside the onMount function because I don't think we have to wait for the page to mount before setting the config.  Waiting for the page to mount also means all the other svelte components are going to go through their first initial render cycle before onMount is called.

File: src/mapper/src/routes/+layout.svelte [hunk 1]
```diff
@@ -13,9 +13,9 @@
 	// Required for PWA to work with svelte
 	const webManifestLink = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');
 
-	onMount(() => {
-		commonStore.setConfig(data.config);
```
Comment (spwoodcock) [inline src/mapper/src/routes/+layout.svelte:17]: Thanks for picking this up! I moved fetching the config to layout.ts but forgot about this part

**Review by spwoodcock — APPROVED** [review]
